#!/bin/bash

# Check if BUILD directory exists
if [ ! -d "BUILD" ]; then
    # If BUILD directory does not exist, create it
    mkdir BUILD
fi

# Change into BUILD directory
cd BUILD

# Run cmake and make
cmake ..
make CXXFLAGS="-g"
